FROM nginx
COPY som /usr/share/nginx/html/
COPY src/assets /usr/share/nginx/html/src/assets/
COPY src/main.architectui.css /usr/share/nginx/html/src/
COPY src/main.architectui.js /usr/share/nginx/html/src/
EXPOSE 80
