// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("test_waterarea_add", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("test_waterarea_add", async function () {
    await driver.get("http://localhost:5173/sign-in");
    await driver.manage().window().setRect({ width: 1900, height: 1020 });
    await driver.findElement(By.id("userInput")).click();
    await driver.findElement(By.id("userInput")).sendKeys("kdb");
    await driver.findElement(By.id("passwordInput")).click();
    console.log("+++++++++++++++++++++++");
    console.log(await driver.findElement(By.id("passwordInput")));
    await driver.findElement(By.id("passwordInput")).sendKeys("kdb");
    console.log("+++++++++++++++++++++++");
    // console.log(await driver.findElement(By.id("id_btn_signin")).click);

    const response = await fetch("http://192.168.140.204:8080/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        ID: "1224",
        Username: "kdb",
        Password: "kdb",
      }),
    });

    await driver.findElement(By.id("id_btn_signin")).click();

    // await driver.findElement(By.css(".login-btn")).click();
    // await driver.wait(
    //   until.elementLocated(By.css(".page-title-subheading")),
    //   30000
    // );
    // await driver.get("http://localhost:5173/waterareas");
    // await driver.wait(until.elementLocated(By.css("tr:nth-child(1) ")), 30000);
    // await driver.findElement(By.css(".fa-fw")).click();
    // await driver.findElement(By.css("#waterarea-modal .modal-body")).click();
    // await driver.findElement(By.id("waterarea-modal-name")).click();
    // await driver
    //   .findElement(By.id("waterarea-modal-name"))
    //   .sendKeys("new water area");
    // await driver.findElement(By.id("waterarea-modal-note")).click();
    // await driver
    //   .findElement(By.id("waterarea-modal-note"))
    //   .sendKeys("new note");
    // await driver.findElement(By.css("#waterarea-modal .btn-primary")).click();
    // await driver.wait(until.elementLocated(By.css("tr:nth-child(1) ")), 30000);
    // await driver.findElement(By.css(".custom-select")).click();
    // await driver.sleep(1000);
    // {
    //   const dropdown = await driver.findElement(By.css(".custom-select"));
    //   await dropdown.findElement(By.xpath("//option[. = '100']")).click();
    // }
    // await driver.sleep(2000);
    // assert(
    //   (await driver
    //     .findElement(By.css("tr:last-child td:nth-child(2)"))
    //     .getText()) == "new water area"
    // );
    // assert(
    //   (await driver
    //     .findElement(By.css("tr:last-child td:nth-child(3)"))
    //     .getText()) == "new note"
    // );
    // await driver.close();
    await driver.sleep(15000);
  });
});
